-- 既存の種目テーブルがある場合に削除
-- DROP TABLE IF EXISTS exercises;

-- 種目テーブルの作成
CREATE TABLE IF NOT EXISTS exercises (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    body_part_id INT NOT NULL,
    FOREIGN KEY (body_part_id) REFERENCES body_parts (id)
);

-- 種目データの挿入
INSERT INTO exercises (name, body_part_id) 
VALUES 
('Around the World', 4),
('Bench Press (Barbell)', 4),
('Bench Press (Cable)', 4),
('Bench Press (Dumbbell)', 4),
('Bench Press (Smith Machine)', 4),
('Bench Press - Wide Grip (Barbell)', 4),
('Cable Crossover', 4),
('Chest Dip', 4),
('Chest Dip (Assisted)', 4),
('Chest Fly', 4),
('Chest Fly (Band)', 4),
('Chest Fly (Dumbbell)', 4),
('Chest Press (Band)', 4),
('Chest Press (Machine)', 4),
('Decline Bench Press (Barbell)', 4),
('Decline Bench Press (Dumbbell)', 4),
('Decline Bench Press (Smith Machine)', 4),
('Floor Press (Barbell)', 4),
('Incline Bench Press (Barbell)', 4),
('Incline Bench Press (Cable)', 4),
('Incline Bench Press (Dumbbell)', 4),
('Incline Bench Press (Smith Machine)', 4),
('Incline Chest Fly (Dumbbell)', 4),
('Incline Chest Press (Machine)', 4),
('Iso-Lateral Chest Press (Machine)', 4),
('Pec Deck (Machine)', 4),
('Pullover (Dumbbell)', 4),
('Pullover (Machine)', 4),
('Push Up', 4),
('Push Up (Band)', 4),
('Push Up (Knees)', 4),
('Back Extension', 3),
('Back Extension (Machine)', 3),
('Bent Over One Arm Row (Dumbbell)', 3),
('Bent Over Row (Band)', 3),
('Bent Over Row (Barbell)', 3),
('Bent Over Row (Dumbbell)', 3),
('Bent Over Row - Underhand (Barbell)', 3),
('Chin Up', 3),
('Chin Up (Assisted)', 3),
('Deadlift (Barbell)', 3),
('Good Morning (Barbell)', 3),
('Incline Row (Dumbbell)', 3),
('Inverted Row (Bodyweight)', 3),
('Iso-Lateral Row (Machine)', 3),
('Kipping Pull Up', 3),
('Kneeling Pulldown (Band)', 3),
('Lat Pulldown (Cable)', 3),
('Lat Pulldown (Machine)', 3),
('Lat Pulldown (Single Arm)', 3),
('Lat Pulldown - Underhand (Band)', 3),
('Lat Pulldown - Underhand (Cable)', 3),
('Lat Pulldown-Wide Grip (Cable)', 3),
('Pendlay Row (Barbell)', 3),
('Pull Up', 3),
('Pull Up (Assisted)', 3),
('Pull Up (Band)', 3),
('Rack Pull (Barbell)', 3),
('Romanian Deadlift (Barbell)', 3),
('Seated Row (Cable)', 3),
('Seated Row (Machine)', 3),
('Seated Wide-Grip Row (Cable)', 3),
('Shrug (Machine)', 3),
('Shrug (Smith Machine)', 3),
('Stiff Leg Deadlift (Barbell)', 3),
('Sumo Deadlift (Barbell)', 3),
('T Bar Row', 3),
('Upright Row (Barbell)', 3),
('Wide Pull Up', 3),
('Box Jump', 5),
('Box Squat (Barbell)', 5),
('Bulgarian Split Squat', 5),
('Cable Pull Through', 5),
('Calf Press on Leg Press', 5),
('Calf Press on Seated Leg Press', 5),
('Deadlift (Band)', 5),
('Deadlift (Dumbbell)', 5),
('Deadlift (Smith Machine)', 5),
('Deficit Deadlift (Barbell)', 5),
('Front Squat (Barbell)', 5),
('Glute Ham Raise', 5),
('Glute Kickback (Machine)', 5),
('Goblet Squat (Kettlebell)', 5),
('Hack Squat', 5),
('Hack Squat (Barbell)', 5),
('Handstand Push Up', 5),
('High Knee Skips', 5),
('Hip Abductor (Machine)', 5),
('Hip Adductor (Machine)', 5),
('Hip Thrust (Barbell)', 5),
('Hip Thrust (Bodyweight)', 5),
('Jump Squat', 5),
('Lateral Box Jump', 5),
('Leg Extension (Machine)', 5),
('Leg Press', 5),
('Lunge (Barbell)', 5),
('Lunge (Bodyweight)', 5),
('Lunge (Dumbbell)', 5),
('Lying Leg Curl (Machine)', 5),
('Mountain Climber', 5),
('Pistol Squat', 5),
('Romanian Deadlift (Dumbbell)', 5),
('Seated Calf Raise (Machine)', 5),
('Seated Calf Raise (Plate Loaded)', 5),
('Seated Leg Curl (Machine)', 5),
('Seated Leg Press (Machine)', 5),
('Single Leg Bridge', 5),
('Squat (Band)', 5),
('Squat (Barbell)', 5),
('Squat (Bodyweight)', 5),
('Squat (Dumbbell)', 5),
('Squat (Machine)', 5),
('Squat (Smith Machine)', 5),
('Standing Calf Raise (Barbell)', 5),
('Standing Calf Raise (Bodyweight)', 5),
('Standing Calf Raise (Dumbbell)', 5),
('Standing Calf Raise (Machine)', 5),
('Standing Calf Raise (Smith Machine)', 5),
('Step-up', 5),
('Stiff Leg Deadlift (Dumbbell)', 5),
('Straight Leg Deadlift (Band)', 5),
('Trap Bar Deadlift', 5),
('Zercher Squat (Barbell)', 5),
('Arnold Press (Dumbbell)', 6),
('Face Pull (Cable)', 6),
('Front Raise (Band)', 6),
('Front Raise (Barbell)', 6),
('Front Raise (Cable)', 6),
('Front Raise (Dumbbell)', 6),
('Front Raise (Plate)', 6),
('Lateral Raise (Band)', 6),
('Lateral Raise (Cable)', 6),
('Lateral Raise (Dumbbell)', 6),
('Lateral Raise (Machine)', 6),
('Overhead Press (Barbell)', 6),
('Overhead Press (Cable)', 6),
('Overhead Press (Dumbbell)', 6),
('Overhead Press (Smith Machine)', 6),
('Push Press', 6),
('Reverse Fly (Cable)', 6),
('Reverse Fly (Dumbbell)', 6),
('Reverse Fly (Machine)', 6),
('Seated Overhead Press (Barbell)', 6),
('Seated Overhead Press (Dumbbell)', 6),
('Shoulder Press (Machine)', 6),
('Shoulder Press (Plate Loaded)', 6),
('Shrug (Barbell)', 6),
('Shrug (Dumbbell)', 6),
('Strict Military Press (Barbell)', 6),
('Upright Row (Dumbbell)', 6),
('Bench Dip', 2),
('Bench Press - Close Grip (Barbell)', 2),
('Bicep Curl (Barbell)', 2),
('Bicep Curl (Cable)', 2),
('Bicep Curl (Dumbbell)', 2),
('Bicep Curl (Machine)', 2),
('Cable Kickback', 2),
('Concentration Curl (Dumbbell)', 2),
('Hammer Curl (Band)', 2),
('Hammer Curl (Cable)', 2),
('Hammer Curl (Dumbbell)', 2),
('Incline Curl (Dumbbell)', 2),
('Preacher Curl (Barbell)', 2),
('Preacher Curl (Dumbbell)', 2),
('Preacher Curl (Machine)', 2),
('Reverse Curl (Band)', 2),
('Reverse Curl (Barbell)', 2),
('Reverse Curl (Dumbbell)', 2),
('Reverse Grip Concentration Curl (Dumbbell)', 2),
('Seated Palms Up Wrist Curl (Dumbbell)', 2),
('Skullcrusher (Barbell)', 2),
('Skullcrusher (Dumbbell)', 2),
('Triceps Dip', 2),
('Triceps Dip (Assisted)', 2),
('Triceps Extension', 2),
('Triceps Extension (Barbell)', 2),
('Triceps Extension (Cable)', 2),
('Triceps Extension (Dumbbell)', 2),
('Triceps Extension (Machine)', 2),
('Triceps Pushdown (Cable - Straight Bar)', 2),
('Upright Row (Cable)', 2),
('Wrist Roller', 2),
('Ab Wheel', 1),
('Bicycle Crunch', 1),
('Cable Crunch', 1),
('Cable Twist', 1),
('Cross Body Crunch', 1),
('Crunch', 1),
('Crunch (Machine)', 1),
('Crunch (Stability Ball)', 1),
('Decline Crunch', 1),
('Flat Knee Raise', 1),
('Flat Leg Raise', 1),
('Hanging Knee Raise', 1),
('Hanging Leg Raise', 1),
('Jackknife Sit Up', 1),
('Knee Raise (Captain''s Chair)', 1),
('Knees to Elbows', 1),
('Oblique Crunch', 1),
('Plank', 1),
('Reverse Crunch', 1),
('Reverse Plank', 1),
('Russian Twist', 1),
('Side Bend (Band)', 1),
('Side Bend (Cable)', 1),
('Side Bend (Dumbbell)', 1),
('Side Plank', 1),
('Sit Up', 1),
('Superman', 1),
('Toes To Bar', 1),
('Torso Rotation (Machine)', 1),
('V Up', 1);